# Generated by Django 5.0.6 on 2024-06-28 03:28

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AccountModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_time', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('last_modified', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('openid', models.CharField(blank=True, default=None, max_length=50, null=True, unique=True, verbose_name='open id')),
                ('nickname', models.CharField(max_length=50, verbose_name='微信昵称')),
                ('avatar_url', models.CharField(blank=True, max_length=255, verbose_name='头像')),
                ('country', models.CharField(blank=True, max_length=30, verbose_name='国家')),
                ('province', models.CharField(blank=True, max_length=30, verbose_name='省份')),
                ('city', models.CharField(blank=True, max_length=30, verbose_name='城市')),
                ('gender', models.CharField(choices=[('0', '未知'), ('1', '男'), ('2', '女')], default='0', max_length=1, verbose_name='性别')),
                ('status', models.CharField(choices=[('0', '删除'), ('1', '正常')], default='1', max_length=1, verbose_name='状态')),
                ('last_login', models.DateTimeField(default=django.utils.timezone.now, verbose_name='上次登陆')),
                ('phone', models.CharField(max_length=11, verbose_name='手机号')),
                ('wechat', models.CharField(blank=True, max_length=50, null=True, verbose_name='微信号')),
                ('session_key', models.CharField(blank=True, max_length=100, null=True, verbose_name='session_key')),
            ],
            options={
                'verbose_name': '小程序用户',
                'verbose_name_plural': '小程序用户',
                'db_table': 'account',
            },
        ),
    ]
